### ISSUE TITLE
no license information provided

### ISSUE THREAD

**Issue by dmhowcroft** [zhijing-jin/genwiki#1]
The repository doesn't provide any information about licensing for the resulting resource or the code used to construct it. It also does not provide information about the licenses for the underlying data. This makes it harder for researchers and businesses to know how they can use the data.

Possible options include the [Open Data Commons](https://opendatacommons.org/) license for the database and Apache 2, MIT, or GPL for the code. I assume Wikipedia and DBPedia's licenses would continue to apply to their data, but that is not clear from this repo.

**Comment by zhijing-jin** [comment]
Thank you for your kind note. I added an MIT License. 

Good luck with playing around with GenWiki :).
