### ISSUE TITLE
It is difficult to generate text without entity information.

### ISSUE THREAD

**Issue by xyjigsaw** [zhijing-jin/genwiki#3]
Hi there, I find that the triples list (graph) doesn't contain all entity information, such as "Lillie P. Bliss Bequest" and "1941" in the first random sample. Moldes (T5 or BART) show worse performance when models generate text using only the graph without entity information in the G2T task. I wonder whether I should combine the graph and entity information together for the G2T task.

**Comment by zhijing-jin** [comment]
Hi, thanks for the note. What you suggested makes lots of sense. I think you can feel free to use both the list of entities and the graph for text generation :).
